services:
  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env


  app:
    container_name: fastapi_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while ! nc -z db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8080'
    volumes:
      - ./app:/src/app
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env

volumes:
  postgres:
    driver: local
